### ISSUE TITLE
Install Lab

### ISSUE THREAD

**Issue by harshal-yb** [harshal-yb/SEBC#2]

**Comment by harshal-yb** [comment]
Issues Faced:
1. Installation of MySQL 5.5 .... changes the repo file to enable repo for 5.5 and it resolved the issue.
2. Faced issues with DB replication needed to update /etc/my.cnf with server ID and binary log format
3. Ran out of space on root file system ...extended the volumes for EC2 instances and rebooted them to resolve the issue
4. The database prepare script suppose to run only for SCM Database, had to drop all the databases and reinstall the cluster.

**Comment by mfernest** [comment]
* Pre-checks look good, except I didn't recognize the reverse-lookup test
* Please look at the cleanup I did on the Markdown. For one, leave a space between `#` marks for headers and the text. For two, use three backticks on a separate line instead of `<code>` tags.

**Comment by mfernest** [comment]
Please clean up the Markdown on the remaining files. I'll give full credit here, but if you want me to look closer at the content it has to be in better format.
