### ISSUE TITLE
Please consolidate all Installation lab issues

### ISSUE THREAD

**Issue by mfernest** [harshal-yb/SEBC#9]
Hi Harshal -

You should have one issue for the work in the Installation section, not a separate issue for each component. 

I realize it will take a little time to build one issue with all those elements but it makes the evaluation process significantly faster for me.

**Comment by harshal-yb** [comment]
Hi Michael,

I have removed all the issues for Install steps and kept one and I will do for each lab now onwards. 

Regards
Harshal

**Comment by harshal-yb** [comment]
Hi Michael,

I have updated the issues faced for install lab in Install lab issue. Please let me know if anything else is needed to consider this issue complete. 

Regards
Harshal
